# Generated by Django 3.1.3 on 2020-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canhost', '0002_auto_20201122_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adress',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
